### ISSUE TITLE
错误反馈

### ISSUE THREAD

**Issue by canyuegongzi** [AlloyTeam/alloy-worker#2]
![image](https://user-images.githubusercontent.com/32031360/114343932-7dea4380-9b91-11eb-903b-86355bec40d0.png)

**Comment by CntChen** [comment]
感谢提醒. 确实有问题. 已经修复, 安装新版本可以解决.
```sh
$ npm i alloy-worker@1.1.0
```

**Comment by canyuegongzi** [comment]
> 感谢提醒. 确实有问题. 已经修复, 安装新版本可以解决.
> 
> ```shell
> $ npm i alloy-worker@1.1.0
> ```

好的
